name: Polyspace CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: debug tree
        shell: cmd
        run: |
          dir
          dir PSTDeneme

      - name: run Polyspace Bug Finder
        shell: cmd
        env:
            POLYSPACE_BIN: "C:\\Program Files\\Polyspace\\R2024b\\polyspace\\bin"
        run: |
          "%POLYSPACE_BIN%\\polyspace-bug-finder.exe" ^
          -project PSTDeneme\\pst_deneme.psprjx ^
          -results-dir results_bug_finder ^
          -output-name bug_finder_results


      - name: Generate Polyspace Report
        shell: cmd
        env:
          POLYSPACE_BIN: "C:\\Program Files\\Polyspace\\R2024b\\polyspace\\bin"
        run: |
          "%POLYSPACE_BIN%\\polyspace-report-generator.exe" ^
            -results-dir results_bug-finder ^
            -report-dir results_bug_finder\\report ^
            -format pdf,html ^
            -include-categories all

      - name: Upload Polyspace Reports
        uses: actions/upload-artifact@v4
        with:
          name: polyspace-reports
          path: results_bug_finder/report/*.pdf
