name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        release: [ 2024b ]

    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: run Polyspace Bug Finder
        shell: cmd
        run: |
          polyspace-bug-finder-navigator ^
            -project pst_deneme.psprj ^
            -results-dir results_bug_finder ^
            -output-name bug_finder_results

      - name: generate Polyspace report
        shell: cmd
        run: |
          polyspace-report-generator ^
            -results-dir results_bug_finder ^
            -report-dir results_bug_finder/report ^
            -format pdf,html ^
            -include-categories all

      - name: upload comparison report
        uses: actions/upload-artifact@v4
        with:
          name: polyspace-reports-${{ matrix.release }}
          path: results_bug_finder/report/*.pdf
